spring:
  application:
    name: hello_world_service
server:
  port: 8081
  servlet:
    context-path:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true